language: node_js
node_js:
  - "4.8.0"
script: npm run $COMMAND
env:
  - COMMAND=test
  - COMMAND=integration MOP_VERSION=. MR_VERSION=16.0.5 DEBUG=true
  - COMMAND=integration MOP_VERSION=. MR_VERSION=latest DEBUG=true
  - COMMAND=integration MOP_VERSION=. MR_VERSION="#master" DEBUG=true
  - COMMAND=integration MOP_VERSION=. MONTAGE_VERSION=16.0.3 DEBUG=true
  - COMMAND=integration MOP_VERSION=. MONTAGE_VERSION=latest DEBUG=true
  - COMMAND=integration MOP_VERSION=. MONTAGE_VERSION="#master" DEBUG=true
notifications:
  irc:
    channels:
      - "chat.freenode.net#montage"
    on_success: false
    template:
      - "%{author} broke the %{repository} tests on %{branch}: %{build_url}"
