language: node_js
node_js:
  - "0.10"
script: npm run $COMMAND
env:
  - COMMAND=test
  - COMMAND=integration MOP_VERSION=. MR_VERSION=0.13
  - COMMAND=integration MOP_VERSION=. MR_VERSION=latest
  - COMMAND=integration MOP_VERSION=. MR_VERSION="#master"
  - COMMAND=integration MOP_VERSION=. MONTAGE_VERSION=0.13
  - COMMAND=integration MOP_VERSION=. MONTAGE_VERSION=latest
  - COMMAND=integration MOP_VERSION=. MONTAGE_VERSION="#master"
